// ===== Scene templates: build(safe, params, scene) -> state ; render(state, T, params, scene) =====
const TEMPLATES = {};
function h(tag,cls,html){ const e=document.createElement(tag); if(cls) e.className=cls; if(html!=null) e.innerHTML=html; return e; }
function cap(safe,text){ if(!text) return null; const c=h('div','caption'); c.innerHTML=faText(text).replace(/\*([^*]+)\*/g,'<b>$1</b>'); safe.appendChild(c); return c; }
function fadeUp(el,p,dy=40){ el.style.opacity=p; el.style.transform=`translateY(${(1-p)*dy}px)`; }
function fadeUpC(el,p,dy=40){ el.style.opacity=p; el.style.transform=`translateY(calc(-50% + ${(1-p)*dy}px))`; }
let _pg=0; function plateSVG(){ const id='pg'+(++_pg); return `<svg viewBox="0 0 300 300"><defs><linearGradient id="${id}" x1="0" x2="1" y1="0" y2="1"><stop offset="0" stop-color="#ffd27a"/><stop offset="1" stop-color="#ff8a1a"/></linearGradient></defs>
  <circle class="ring" cx="150" cy="150" r="128" fill="none" stroke="url(#${id})" stroke-width="30" stroke-linecap="round" pathLength="100" stroke-dasharray="100" stroke-dashoffset="100" transform="rotate(-90 150 150)"/>
  <circle class="core" cx="150" cy="150" r="46" fill="#ffb020"/>
  <circle class="ring2" cx="150" cy="150" r="88" fill="none" stroke="rgba(255,255,255,.18)" stroke-width="4" pathLength="100" stroke-dasharray="100" stroke-dashoffset="100" transform="rotate(90 150 150)"/></svg>`; }

// ---------- title ----------
TEMPLATES.title = {
  build(safe,p){ const w=h('div','', ''); w.style.cssText='position:absolute;left:0;right:0;top:50%;transform:translateY(-52%)';
    const pl=h('div','plateBig',plateSVG()); const k=h('div','kick',faText(p.kicker||'')); const big=h('div','big',faText(p.title||'وزنه'));
    const sub=h('div','sub'); const words=buildWords(sub,p.subtitle||''); const d=h('div','date',faText(p.date||''));
    w.append(pl,k,big,sub,d); safe.appendChild(w); return {pl,k,big,sub,words,d, ring:pl.querySelector('.ring'), ring2:pl.querySelector('.ring2'), core:pl.querySelector('.core')}; },
  render(s,T){ const r=seg(T,0.1,1.6,E.inOut); s.ring.style.strokeDashoffset=100-100*r; s.ring2.style.strokeDashoffset=100-100*seg(T,0.5,1.4,E.inOut);
    const c=seg(T,0.9,0.8,E.outBack); s.core.setAttribute('r',46*c); s.pl.style.transform=`scale(${lerp(.9,1,seg(T,0,1.5))}) rotate(${T*6}deg)`;
    fadeUp(s.k,seg(T,1.2,0.6)); const b=seg(T,1.5,0.9,E.outQ); s.big.style.opacity=b; s.big.style.transform=`translateY(${(1-b)*60}px) scale(${lerp(.92,1,b)})`; s.big.style.letterSpacing=lerp(14,0,b)+'px';
    revealWords(s.words,T,2.3,0.12); fadeUp(s.d,seg(T,3.2,0.7)); }
};
// ---------- chapter ----------
TEMPLATES.chapter = {
  build(safe,p){ const w=h('div',''); w.style.cssText='position:absolute;left:0;right:0;top:50%;transform:translateY(-50%)';
    const n=h('div','n',fa(p.num??1)); const lbl=h('div','lbl',faText(p.label||'سال')); const hh=h('div','h'); const words=buildWords(hh,p.title||''); const rule=h('div','rule'); const s=h('div','s',faText(p.sub||''));
    w.append(n,lbl,hh,rule,s); safe.appendChild(w); return {n,lbl,hh,words,rule,s}; },
  render(s,T){ const a=seg(T,0,0.9,E.outQ); s.n.style.opacity=a; s.n.style.transform=`translateY(${(1-a)*80}px) scale(${lerp(1.3,1,a)})`; fadeUp(s.lbl,seg(T,0.5,0.6));
    revealWords(s.words,T,0.9,0.1); s.rule.style.width=(160*seg(T,1.3,0.7))+'px'; fadeUp(s.s,seg(T,1.6,0.7)); }
};
// ---------- text (kinetic typography) ----------
TEMPLATES.text = {
  build(safe,p,sc){ if(p.size) sc._el && sc._el.classList.add(p.size); const box=h('div','lines'); const lines=(p.lines||[]).map(t=>{ const ln=h('div','ln'+(p.align==='center'?' center':'')); const words=buildWords(ln,t); box.appendChild(ln); return {ln,words}; });
    if(p.kicker){ const k=h('div','kicker'+(p.kickerColor?' '+p.kickerColor:''),faText(p.kicker)); box.prepend(k); }
    safe.appendChild(box); const c=cap(safe,p.caption); return {lines,box,c,size:p.size}; },
  render(s,T,p,sc){ if(s.size && sc._el && !sc._el.classList.contains(s.size)) sc._el.classList.add(s.size);
    const total = s.lines.reduce((a,l)=>a+l.words.length,0); const avail=Math.max(1.5,(sc.dur-2.4-0.25*s.lines.length)); const per=clamp(avail/Math.max(total,1),0.08,0.27);
    let t0=0.3; for(const l of s.lines){ revealWords(l.words,T,t0,per); t0+=l.words.length*per+0.25; }
    if(s.c) fadeUp(s.c,seg(T,Math.min(t0,sc.dur-1.2),0.6)); }
};
// ---------- montage (rapid dated beats) ----------
TEMPLATES.montage = {
  build(safe,p){ const box=h('div','mont'); if(p.kicker) box.appendChild(h('div','kicker',faText(p.kicker))); const items=(p.items||[]).map(it=>{ const e=h('div','it '+(it.tone||'')); e.append(h('div','d',faText(it.date||'')),h('div','t',faText(it.text||'').replace(/\*([^*]+)\*/g,'<span class="hl">$1</span>'))); box.appendChild(e); return e; }); safe.appendChild(box); const c=cap(safe,p.caption); return {items,c}; },
  render(s,T,p,sc){ const n=s.items.length; const per=Math.max(0.5,(sc.dur-1.8)/Math.max(n,1)); s.items.forEach((e,i)=>{ const q=seg(T,0.3+i*per,0.45,E.outBack); e.style.opacity=q; e.style.transform=`translateX(${(1-q)*-60}px)`; }); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
// ---------- counter ----------
TEMPLATES.counter = {
  build(safe,p){ const box=h('div','counters'+(p.row?' cntRow':'')); if(p.kicker){ const k=h('div','kicker',faText(p.kicker)); k.style.textAlign='center'; box.appendChild(k);} const items=(p.items||[]).map(it=>{ const e=h('div','cnt'+(p.items.length>1?' sm':'')); const v=h('div','v '+(it.color||'')); const l=h('div','l',faText(it.label||'')); e.append(v,l); box.appendChild(e); return {e,v,l,it}; }); safe.appendChild(box); const c=cap(safe,p.caption); return {items,c}; },
  render(s,T,p,sc){ s.items.forEach((o,i)=>{ const st=0.3+i*0.7; const q=seg(T,st,1.8,E.outExpo); const val=lerp(o.it.from||0,o.it.value||0,q); const dec=o.it.decimals||0; let txt=dec?val.toFixed(dec):fmtNum(val); txt=(o.it.prefix||'')+txt+(o.it.suffix||''); o.v.textContent=fa(txt); const a=seg(T,st,0.5); o.e.style.opacity=a; o.e.style.transform=`translateY(${(1-a)*50}px)`; }); if(s.c) fadeUp(s.c,seg(T,1.4+0.5*s.items.length,0.6)); }
};
// ---------- chart ----------
TEMPLATES.chart = {
  build(safe,p){ const box=h('div','chartBox'); box.appendChild(h('div','h',faText(p.title||''))); if(p.sub) box.appendChild(h('div','s',faText(p.sub)));
    const W=920,H=640,L=90,R=30,Tp=40,B=70; const pts=p.points||[]; const xl=p.xlabels||[]; const ymax=p.ymax||Math.max(...pts,1)*1.15; const n=pts.length;
    const X=i=>L+(W-L-R)*(n>1?i/(n-1):0), Y=v=>Tp+(H-Tp-B)*(1-v/ymax);
    let svg=`<svg viewBox="0 0 ${W} ${H}"><defs><linearGradient id="ag" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="${p.color||'#2FD58F'}" stop-opacity=".35"/><stop offset="1" stop-color="${p.color||'#2FD58F'}" stop-opacity="0"/></linearGradient></defs>`;
    for(let g=0;g<=4;g++){ const y=Tp+(H-Tp-B)*g/4; svg+=`<line class="gl" x1="${L}" x2="${W-R}" y1="${y}" y2="${y}"/><text x="${L-14}" y="${y+8}" text-anchor="end">${fa(fmtNum(ymax*(1-g/4)))}</text>`; }
    svg+=`<line class="axis" x1="${L}" x2="${W-R}" y1="${H-B}" y2="${H-B}"/>`;
    xl.forEach((lb,i)=>{ if(n>1){ const x=X(Math.round(i*(n-1)/Math.max(xl.length-1,1))); svg+=`<text x="${x}" y="${H-B+40}" text-anchor="middle">${faText(lb)}</text>`; } });
    if(p.kind==='bar'){ const bw=(W-L-R)/n*0.6; pts.forEach((v,i)=>{ svg+=`<rect class="bar" data-i="${i}" x="${X(i)-bw/2}" y="${Y(v)}" width="${bw}" height="${H-B-Y(v)}" rx="8" fill="${p.color||'#2FD58F'}"/>`; }); }
    else { const d=pts.map((v,i)=>`${i?'L':'M'}${X(i)},${Y(v)}`).join(' '); const area=d+` L${X(n-1)},${H-B} L${X(0)},${H-B} Z`; svg+=`<path class="area" d="${area}" fill="url(#ag)"/><path class="line" d="${d}" fill="none" stroke="${p.color||'#2FD58F'}" stroke-width="7" stroke-linecap="round" stroke-linejoin="round" pathLength="100" stroke-dasharray="100" stroke-dashoffset="100"/><circle class="dot" r="14" fill="${p.color||'#2FD58F'}" stroke="#0A0D12" stroke-width="5"/><text class="val" text-anchor="middle"></text>`; }
    svg+='</svg>'; const sv=h('div','',svg); box.appendChild(sv); safe.appendChild(box); const c=cap(safe,p.caption);
    return {box,c,line:sv.querySelector('.line'),area:sv.querySelector('.area'),dot:sv.querySelector('.dot'),val:sv.querySelector('.val'),bars:[...sv.querySelectorAll('.bar')],pts,X,Y,H,B,kind:p.kind,fmt:p.valueSuffix||'',prefix:p.valuePrefix||''}; },
  render(s,T,p,sc){ const dur=Math.max(2,Math.min(4.5,sc.dur-2)); const q=seg(T,0.6,dur,E.inOut);
    if(s.kind==='bar'){ s.bars.forEach((b,i)=>{ const bq=seg(T,0.5+i*(dur/Math.max(s.bars.length,1)),0.6,E.outBack); const full=+b.getAttribute('height'); const y0=s.H-s.B; b.setAttribute('height',Math.max(0,full*bq)); b.setAttribute('y',y0-full*bq); }); }
    else { s.line.style.strokeDashoffset=100-100*q; s.area.style.opacity=q; const n=s.pts.length; const f=q*(n-1); const i=Math.min(n-2,Math.floor(f)); const fr=f-i; const v=n>1?lerp(s.pts[i],s.pts[i+1],fr):s.pts[0]; const x=n>1?lerp(s.X(i),s.X(i+1),fr):s.X(0); const y=s.Y(v); s.dot.setAttribute('cx',x); s.dot.setAttribute('cy',y); s.dot.style.opacity=q>0.02?1:0; s.val.setAttribute('x',x); s.val.setAttribute('y',y-30); s.val.textContent=fa(s.prefix+fmtNum(v)+s.fmt); s.val.style.opacity=q>0.05?1:0; }
    fadeUpC(s.box,seg(T,0,0.6)); if(s.c) fadeUp(s.c,seg(T,dur+0.8,0.6)); }
};
// ---------- timeline / checklist ----------
TEMPLATES.timeline = {
  build(safe,p){ const box=h('div','tl'); if(p.title) box.appendChild(h('div','h',faText(p.title))); const items=(p.items||[]).map(it=>{ const e=h('div','it'+(it.state==='next'?' dim':'')); const d=h('div','dot '+(it.state||'')); const tx=h('div','tx',faText(it.text||'').replace(/\*([^*]+)\*/g,'<span class="hl">$1</span>')+(it.sub?`<small>${faText(it.sub)}</small>`:'')); e.append(d,tx); box.appendChild(e); return {e,d,it}; }); safe.appendChild(box); const c=cap(safe,p.caption); return {items,c}; },
  render(s,T,p,sc){ const n=s.items.length; const per=Math.max(0.4,Math.min(1.1,(sc.dur-2)/Math.max(n,1))); s.items.forEach((o,i)=>{ const q=seg(T,0.4+i*per,0.5,E.out); o.e.style.opacity=q; o.e.style.transform=`translateX(${(1-q)*-40}px)`; const st=o.it.state||'done'; const on=T>0.4+i*per+0.55; o.d.className='dot '+(on?st:''); }); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
TEMPLATES.checklist = TEMPLATES.timeline;
// ---------- quote ----------
TEMPLATES.quote = {
  build(safe,p){ const box=h('div','quote'); const card=h('div','card'); const mark=h('div','mark','”'); const stars=h('div','stars'); const q=h('div','q'); const words=buildWords(q,p.text||''); const a=h('div','a',`<span>${faText(p.author||'')}</span><span>${faText(p.source||'')}</span>`); card.append(mark,stars,q,a); box.appendChild(card); safe.appendChild(box); const c=cap(safe,p.caption); return {box,card,stars,words,a,c,n:p.stars??5}; },
  render(s,T,p,sc){ fadeUpC(s.box,seg(T,0,0.7)); let st=''; for(let i=0;i<5;i++){ st+= (i<s.n && T>0.5+i*0.18)?'★':'☆'; } s.stars.textContent=st; revealWords(s.words,T,1.4,clamp((sc.dur-3.5)/Math.max(s.words.length,1),0.08,0.3)); fadeUp(s.a,seg(T,sc.dur-1.8,0.6)); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
// ---------- decision ----------
TEMPLATES.decision = {
  build(safe,p){ const box=h('div','dec'); if(p.kicker) box.appendChild(h('div','kicker',faText(p.kicker))); const q=h('div','q'); const qw=buildWords(q,p.question||''); box.appendChild(q); const opts=(p.options||[]).map(o=>{ const e=h('div','card opt'+(o.chosen?' ch':'')); e.append(h('div','t',faText(o.text||''))); const pr=h('div','p',`<span>${faText(p.plabel||'احتمال')}</span><div class="bar"><i></i></div><b class="pv">۰٪</b>`); e.appendChild(pr); if(o.chosen) e.appendChild(h('div','tag',faText(o.tag||'شدنی‌ترین'))); box.appendChild(e); return {e,bar:pr.querySelector('i'),pv:pr.querySelector('.pv'),o}; }); safe.appendChild(box); const c=cap(safe,p.caption); return {qw,opts,c}; },
  render(s,T,p,sc){ revealWords(s.qw,T,0.2,0.12); const t0=0.2+s.qw.length*0.12+0.3; s.opts.forEach((o,i)=>{ const a=seg(T,t0+i*0.45,0.6,E.outBack); o.e.style.opacity=a*( (T>sc.dur-2.2 && !o.o.chosen)?0.45:1); o.e.style.transform=`translateY(${(1-a)*50}px)`; const b=seg(T,t0+0.6+i*0.45,1.2,E.outExpo); const pct=Math.round((o.o.p||0)*100*b); o.bar.style.width=pct+'%'; o.pv.textContent=fa(pct)+'٪'; if(o.o.chosen){ const g=seg(T,sc.dur-2.4,0.6); o.e.style.boxShadow=`0 0 0 ${2*g}px var(--amber), 0 30px 80px rgba(255,176,32,${.15*g})`; o.e.querySelector('.tag').style.opacity=g; o.e.style.transform+=` scale(${lerp(1,1.03,g)})`; } }); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
// ---------- low point ----------
TEMPLATES.low = {
  build(safe,p,sc){ const rain=h('div','rain'); const drops=[]; for(let i=0;i<70;i++){ const d=document.createElement('i'); const x=((i*173)%1080); const sp=900+((i*97)%500); const off=(i*311)%2000; d.style.left=x+'px'; d.style.height=(80+(i*53)%90)+'px'; rain.appendChild(d); drops.push({d,sp,off}); } sc._rain=rain;
    const w=h('div',''); w.style.cssText='position:absolute;left:0;right:0;top:50%;transform:translateY(-55%)'; const clock=h('div','clock',p.time||'02:47'); const cl=h('div','clockL',faText(p.timeLabel||'بعد از شیفت شب')); const lines=h('div','lines'); const ls=(p.lines||[]).map(t=>{ const ln=h('div','ln'); const words=buildWords(ln,t); lines.appendChild(ln); return {ln,words}; }); w.append(clock,cl,lines); safe.appendChild(w); const c=cap(safe,p.caption); return {drops,clock,cl,ls,c,rain}; },
  render(s,T,p,sc){ if(s.rain && !s.rain.parentNode){ sc._el.insertBefore(s.rain, sc._el.firstChild); } s.drops.forEach(o=>{ const y=((T*o.sp+o.off)%2100)-150; o.d.style.transform=`translateY(${y}px)`; });
    const a=seg(T,0.2,1.2); s.clock.style.opacity=a*(0.75+0.25*Math.sin(T*3)); fadeUp(s.cl,seg(T,0.8,0.6)); let t0=1.6; const per=clamp((sc.dur-3.6-0.3*s.ls.length)/Math.max(s.ls.reduce((a,l)=>a+l.words.length,0),1),0.08,0.27); for(const l of s.ls){ revealWords(l.words,T,t0,per,20); t0+=l.words.length*per+0.3; } if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
// ---------- year card ----------
TEMPLATES.year = {
  build(safe,p){ const box=h('div',''); box.style.cssText='position:absolute;left:0;right:0;top:50%;transform:translateY(-50%)'; const top=h('div','top'); const n=h('div','n',fa(p.year??1)); const nl=h('div','nl',faText(p.label||'سال')); top.append(n,nl); const hh=h('div','h'); const hw=buildWords(hh,p.headline||''); const tiles=h('div','tiles'); const ts=(p.tiles||[]).map(t=>{ const e=h('div','card tile'); const v=h('div','v '+(t.color||'')); const l=h('div','l',faText(t.label||'')); e.append(v,l); tiles.appendChild(e); return {e,v,t}; }); const lines=h('div','lines'); const ls=(p.lines||[]).map(t=>{ const ln=h('div','ln',faText(t).replace(/\*([^*]+)\*/g,'<b>$1</b>')); lines.appendChild(ln); return ln; }); box.append(top,hh,tiles,lines); safe.appendChild(box); return {top,n,hw,ts,ls}; },
  render(s,T,p,sc){ const a=seg(T,0,0.8,E.outQ); s.top.style.opacity=a; s.top.style.transform=`translateX(${(1-a)*-60}px)`; revealWords(s.hw,T,0.6,0.1); const t0=0.6+s.hw.length*0.1+0.2; s.ts.forEach((o,i)=>{ const q=seg(T,t0+i*0.25,0.6,E.outBack); o.e.style.opacity=q; o.e.style.transform=`translateY(${(1-q)*40}px)`; const c=seg(T,t0+i*0.25,1.6,E.outExpo); const v=lerp(o.t.from||0,o.t.value||0,c); const txt=(o.t.prefix||'')+(o.t.decimals?v.toFixed(o.t.decimals):fmtNum(v))+(o.t.suffix||''); o.v.textContent=fa(txt); }); s.ls.forEach((ln,i)=>fadeUp(ln,seg(T,t0+1.4+i*0.35,0.6))); }
};
// ---------- map (abstract constellation) ----------
TEMPLATES.map = {
  build(safe,p){ const box=h('div','map'); if(p.title) box.appendChild(h('div','h',faText(p.title))); const W=920,H=1000; const nodes=p.nodes||[]; let svg=`<svg viewBox="0 0 ${W} ${H}">`; (p.edges||[]).forEach((e,i)=>{ const a=nodes[e[0]],b=nodes[e[1]]; if(a&&b) svg+=`<line class="edge" data-i="${i}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="rgba(255,176,32,.5)" stroke-width="3" stroke-dasharray="8 10" pathLength="100" stroke-dashoffset="100" style="stroke-dasharray:100"/>`; }); nodes.forEach((n,i)=>{ svg+=`<g class="node" data-i="${i}"><circle class="pulse" cx="${n.x}" cy="${n.y}" r="0" fill="none" stroke="${n.color||'#FFB020'}" stroke-width="3"/><circle class="pulse2" cx="${n.x}" cy="${n.y}" r="0" fill="none" stroke="${n.color||'#FFB020'}" stroke-width="2"/><circle class="core" cx="${n.x}" cy="${n.y}" r="0" fill="${n.color||'#FFB020'}"/><text x="${n.x}" y="${n.y-(n.r||14)-22}" text-anchor="middle">${faText(n.name)}</text>${n.sub?`<text class="sub" x="${n.x}" y="${n.y+(n.r||14)+38}" text-anchor="middle">${faText(n.sub)}</text>`:''}</g>`; }); svg+='</svg>'; const sv=h('div','',svg); box.appendChild(sv); safe.appendChild(box); const c=cap(safe,p.caption); return {nodes:[...sv.querySelectorAll('.node')],edges:[...sv.querySelectorAll('.edge')],data:nodes,c,box}; },
  render(s,T,p,sc){ fadeUpC(s.box,seg(T,0,0.6)); const n=s.data.length; const per=Math.max(0.35,Math.min(1.2,(sc.dur-2.5)/Math.max(n,1))); s.nodes.forEach((g,i)=>{ const st=(s.data[i].t!=null?s.data[i].t:0.5+i*per); const q=seg(T,st,0.6,E.outBack); const r=s.data[i].r||14; g.querySelector('.core').setAttribute('r',r*q); g.style.opacity=q; const ph=((T-st)*1.2)%1; const vis=T>st; g.querySelector('.pulse').setAttribute('r',vis?r+ph*40:0); g.querySelector('.pulse').style.opacity=vis?(1-ph)*0.8:0; const ph2=((T-st)*1.2+0.5)%1; g.querySelector('.pulse2').setAttribute('r',vis?r+ph2*40:0); g.querySelector('.pulse2').style.opacity=vis?(1-ph2)*0.5:0; }); s.edges.forEach((e,i)=>{ const st=0.9+i*per; e.style.strokeDashoffset=100-100*seg(T,st,0.9,E.inOut); }); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
// ---------- chat (full-screen messenger) ----------
TEMPLATES.chat = {
  build(safe,p){ const box=h('div','chatFull'); const hd=h('div','hd'); hd.append(h('div','av',faText((p.title||'گ')[0])),h('div','',`<div class="n">${faText(p.title||'')}</div><div class="s">${faText(p.sub||'آنلاین')}</div>`)); const msgs=h('div','msgs'); const items=(p.messages||[]).map(m=>{ const b=h('div','bub '+(m.me?'me':(m.ai?'them ai':'them'))); if(m.from&&!m.me) b.appendChild(h('div','who',faText(m.from))); const tx=h('div','tx',faText(m.text||'')); b.appendChild(tx); msgs.appendChild(b); return {b,m,tx}; }); box.append(hd,msgs); safe.appendChild(box); const c=cap(safe,p.caption); return {items,c}; },
  render(s,T,p,sc){ const n=s.items.length; const per=Math.max(0.7,Math.min(2.2,(sc.dur-2)/Math.max(n,1))); s.items.forEach((o,i)=>{ const st=0.4+i*per; const q=seg(T,st,0.45,E.outBack); o.b.style.opacity=q; o.b.style.transform=`translateY(${(1-q)*30}px) scale(${lerp(.9,1,q)})`; o.b.style.display = T>st-0.35?'block':'none'; if(T<st){ o.tx.innerHTML='<span class="typing"><i></i><i></i><i></i></span>'; } else { o.tx.textContent=faText(o.m.text||''); } }); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.4,0.6)); }
};
// ---------- phone (app mockup) ----------
function phoneShell(safe,scale=1){ const wrap=h('div','phoneWrap'); wrap.style.transform=`translate(-50%,-50%) scale(${scale})`; const ph=h('div','phone'); const sc=h('div','screen'); ph.append(h('div','notch'),sc); wrap.appendChild(ph); safe.appendChild(wrap); const status=h('div','status',`<span>${fa('14:37')}</span><span>▮▮▮ ${fa('87')}٪</span>`); sc.appendChild(status); return {wrap,ph,sc}; }
const PHONE_SCREENS = {
  log(sc,p){ const bar=h('div','appbar',`<div class="t">وزنه</div><div class="r">${faText(p.day||'برنامه‌ی امروز · پا')}</div>`); const body=h('div','body'); const rows=(p.rows||[{n:'اسکوات',c:'SQ-01',s:'4×8',prev:'80',now:'82.5'},{n:'پرس پا',c:'LP-04',s:'4×12',prev:'140',now:'150'},{n:'جلو پا',c:'LE-02',s:'3×15',prev:'45',now:'45'},{n:'لانج',c:'LG-03',s:'3×12',prev:'20',now:'22.5'},{n:'ساق پا',c:'CR-01',s:'4×20',prev:'60',now:'65'}]).map(r=>{ const e=h('div','row'); e.innerHTML=`<div><div class="nm">${faText(r.n)}<span class="code">${r.c}</span></div><div class="meta">${faText(r.s)} · دفعه‌ی قبل: ${fa(r.prev)} kg</div></div><div class="kg">${fa(r.prev)}</div><div class="chk"></div>`; body.appendChild(e); return {e,r,kg:e.querySelector('.kg'),chk:e.querySelector('.chk')}; }); const fab=h('div','fab','✦'); body.appendChild(fab); sc.append(bar,body); return {rows,fab,
    render(T,dur){ const per=Math.max(0.6,(dur-2)/rows.length); rows.forEach((o,i)=>{ const st=0.6+i*per; const q=seg(T,st,0.4); o.e.style.opacity=q; o.e.style.transform=`translateY(${(1-q)*20}px)`; const typed=T>st+0.5; o.kg.textContent=fa(typed?o.r.now:o.r.prev); o.kg.className='kg'+(typed?' on':''); o.chk.className='chk'+(T>st+0.9?' on':''); }); fab.style.transform=`scale(${1+0.06*Math.sin(T*4)})`; } }; },
  playstore(sc,p){ const body=h('div','ps'); body.innerHTML=`<div class="hdr"><div class="icon"><i></i></div><div><div class="nm">Vazne · وزنه</div><div class="dev">Mehrdad Khani</div></div></div><div class="stats"><div><b>${p.rating||'—'}★</b>rating</div><div><b>${p.installs||'—'}</b>installs</div><div><b>3+</b>rated for</div></div><div class="btn"><div class="fill" style="width:0%"></div><span>Install</span></div><div class="pill ${p.live?'live':''}">${p.status||'Closed testing · 12 testers · 14 days'}</div><div class="shot">وزنه</div>`; sc.appendChild(body); const fill=body.querySelector('.fill'), lbl=body.querySelector('.btn span'), stats=body.querySelectorAll('.stats b'); return {render(T,dur){ fadeUp(body,seg(T,0.2,0.6)); const q=seg(T,1.2,2.2,E.inOut); fill.style.width=(q*100)+'%'; lbl.textContent= q>=1?'Open':(q>0?Math.round(q*100)+'%':'Install'); } }; },
  chat(sc,p){ const bar=h('div','appbar',`<div class="t">وزنه</div><div class="r">مربی هوشمند</div>`); const body=h('div','body'); body.style.display='flex'; body.style.flexDirection='column'; body.style.justifyContent='flex-end'; body.style.paddingBottom='40px'; const items=(p.messages||[{me:true,text:'زانوم موقع اسکوات صدا می‌ده، ادامه بدم؟'},{ai:true,text:'اگه درد نداری، صدا معمولاً طبیعیه. امروز وزنه رو ۱۰٪ کم کن و عمق رو کنترل کن. دفعه‌ی قبل ۸۰ زدی؛ ۷۲٫۵ بزن.'},{me:true,text:'باشه. ست بعدی چی؟'},{ai:true,text:'همون ۷۲٫۵، ۸ تکرار، تمپوی ۳ ثانیه پایین.'}]).map(m=>{ const b=h('div','bub '+(m.me?'me':'them ai')); const tx=h('div','tx',faText(m.text)); b.appendChild(tx); body.appendChild(b); return {b,tx,m}; }); sc.append(bar,body); return {render(T,dur){ const per=Math.max(0.8,(dur-1.5)/items.length); items.forEach((o,i)=>{ const st=0.5+i*per; const q=seg(T,st,0.4,E.outBack); o.b.style.opacity=q; o.b.style.display=T>st-0.4?'block':'none'; o.b.style.transform=`translateY(${(1-q)*20}px)`; o.tx.innerHTML = T<st? '<span class="typing"><i></i><i></i><i></i></span>' : faText(o.m.text); }); } }; },
  scan(sc,p){ const body=h('div','body'); body.style.padding='0'; const paper=h('div','paper',`<div class="ph">${faText(p.paperTitle||'برنامه‌ی هفته — روز ۱')}</div>`+(p.paperLines||['اسکوات ۴×۸','پرس پا ۴×۱۲','جلو پا ۳×۱۵','لانج ۳×۱۲','ساق ۴×۲۰']).map(l=>`<div class="pl">${faText(l)}</div>`).join('')); const frame=h('div','frameC'); const line=h('div','scanline'); const parsed=h('div','parsed'); const rows=(p.rows||[{n:'اسکوات',c:'SQ-01',s:'4×8'},{n:'پرس پا',c:'LP-04',s:'4×12'},{n:'جلو پا',c:'LE-02',s:'3×15'},{n:'لانج',c:'LG-03',s:'3×12'}]).map(r=>{ const e=h('div','row'); e.innerHTML=`<div><div class="nm">${faText(r.n)}<span class="code">${r.c}</span></div><div class="meta">${faText(r.s)}</div></div><div class="chk on"></div>`; parsed.appendChild(e); return e; }); body.append(paper,frame,line,parsed); sc.appendChild(body); return {render(T,dur){ const q=seg(T,0.8,2.0,E.inOut); line.style.top=(40+q*520)+'px'; line.style.opacity=(T>0.8&&T<2.9)?1:0; frame.style.opacity=seg(T,0.3,0.4); paper.style.opacity=seg(T,0,0.5); rows.forEach((e,i)=>{ const a=seg(T,2.9+i*0.35,0.45,E.outBack); e.style.opacity=a; e.style.transform=`translateY(${(1-a)*20}px)`; }); } }; },
  notif(sc,p){ const body=h('div','body'); body.style.padding='0'; body.style.top='0'; const time=h('div','lockTime',fa(p.time||'07:12')); const date=h('div','lockDate',faText(p.date||'سه‌شنبه ۱۴ مهر')); const box=h('div','notifs'); const items=(p.items||[{app:'Google Play Console',t:'Your app is live',b:'Vazne is now available on Google Play.'},{app:'Google Play',t:'★★★★★ نظر جدید',b:'بالاخره یه اپ که برنامه‌ی دست‌نویس مربی رو می‌فهمه.'},{app:'Vazne Backend',t:'اشتراک جدید',b:'CAD 4.99 · Mississauga'}]).map(it=>{ const e=h('div','ntf',`<div class="ap"><span>${faText(it.app)}</span><span>${faText(it.when||'الان')}</span></div><div class="ti">${faText(it.t)}</div><div class="bd">${faText(it.b)}</div>`); box.appendChild(e); return e; }); body.append(time,date,box); sc.appendChild(body); return {render(T,dur){ fadeUp(time,seg(T,0,0.6)); fadeUp(date,seg(T,0.2,0.6)); const per=Math.max(0.8,(dur-2)/items.length); items.forEach((e,i)=>{ const q=seg(T,0.9+i*per,0.5,E.outBack); e.style.opacity=q; e.style.transform=`translateY(${(1-q)*-30}px) scale(${lerp(.95,1,q)})`; }); } }; },
  stats(sc,p){ const bar=h('div','appbar',`<div class="t">وزنه</div><div class="r">آمار من</div>`); const body=h('div','body'); const tiles=(p.tiles||[{v:'42',l:'جلسه'},{v:'18,400',l:'کیلو حجم کل'},{v:'12',l:'هفته پشت‌سرهم'},{v:'+11٪',l:'رشد اسکوات'}]).map(t=>{ const e=h('div','row'); e.style.flexDirection='column'; e.style.alignItems='flex-start'; e.innerHTML=`<div class="num" style="font-size:64px;color:var(--amber)">${fa(t.v)}</div><div class="meta">${faText(t.l)}</div>`; body.appendChild(e); return e; }); sc.append(bar,body); return {render(T){ tiles.forEach((e,i)=>{ const q=seg(T,0.4+i*0.3,0.5,E.outBack); e.style.opacity=q; e.style.transform=`translateY(${(1-q)*20}px)`; }); } }; },
};
TEMPLATES.phone = {
  build(safe,p){ const {wrap,sc}=phoneShell(safe,p.scale||1); const screen=(PHONE_SCREENS[p.screen]||PHONE_SCREENS.log)(sc,p.data||{}); const c=cap(safe,p.caption); if(p.kicker){ const k=h('div','kicker',faText(p.kicker)); k.style.cssText='position:absolute;top:0;left:0;right:0;text-align:center'; safe.appendChild(k); } return {wrap,screen,c}; },
  render(s,T,p,sc){ const a=seg(T,0,0.8,E.outQ); s.wrap.style.opacity=a; s.wrap.style.transform=`translate(-50%,-50%) scale(${(p.scale||1)*lerp(.94,1,a)}) rotate(${lerp(-3,0,a)}deg)`; s.screen.render(T,sc.dur); if(s.c) fadeUp(s.c,seg(T,sc.dur-1.6,0.6)); }
};
// ---------- end ----------
TEMPLATES.end = {
  build(safe,p){ const w=h('div',''); w.style.cssText='position:absolute;left:0;right:0;top:50%;transform:translateY(-50%)'; const pl=h('div','plateBig',plateSVG()); pl.style.width='200px'; pl.style.height='200px'; const big=h('div','big',faText(p.title||'وزنه')); const lines=(p.lines||[]).map(t=>{ const ln=h('div','ln'); ln._w=buildWords(ln,t); return ln; }); const sm=h('div','sm',(p.small||[]).map(faText).join('<br>')); w.append(pl,big,...lines,sm); safe.appendChild(w); return {pl,big,lines,sm,ring:pl.querySelector('.ring'),ring2:pl.querySelector('.ring2')}; },
  render(s,T,p,sc){ s.ring.style.strokeDashoffset=100-100*seg(T,0,1.4,E.inOut); s.ring2.style.strokeDashoffset=100-100*seg(T,0.3,1.4,E.inOut); s.pl.style.transform=`rotate(${T*8}deg)`; fadeUp(s.big,seg(T,0.8,0.8)); let t0=1.6; s.lines.forEach(ln=>{ revealWords(ln._w,T,t0,0.14); t0+=ln._w.length*0.14+0.4; }); fadeUp(s.sm,seg(T,Math.min(t0,sc.dur-2.5),0.8)); }
};
